using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BrainPower : MonoBehaviour
{
    [SerializeField] private List<Note_instantiate> Notes;
    void Start()
    {
        StartCoroutine(BrainPowerGame());
    }

    IEnumerator BrainPowerGame()
    {
        yield return new WaitForSeconds(0.330f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Heal_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Heal_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Heal_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Heal_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Heal_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.264f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Heal_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.177f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Small_Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Heal_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.706f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.706f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.706f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.264f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.264f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.264f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.264f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Small_Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Small_Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.353f);
        Notes[0].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[2].Small_Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[0].Ins_Note();
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        yield return new WaitForSeconds(0.176f);
        Notes[5].Small_Ins_Note();
        Invoke("GameEnd", 9);
    }

    public void GameEnd()
    {
        Scoremanager.Instance.Img_Loading(2);
    }
}
