using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NyanCat : MonoBehaviour
{
    [SerializeField] private List<Note_instantiate> Notes;
    void Start()
    {
        StartCoroutine(NyanCatGame());
    }

    IEnumerator NyanCatGame()
    {
        yield return new WaitForSeconds(1.229f);
        Notes[0].Small_Ins_Note();
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[0].Small_Ins_Note();
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[0].Small_Ins_Note();
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[0].Small_Ins_Note();
        Notes[1].Small_Ins_Note();
        yield return new WaitForSeconds(0.095f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[5].Heal_Ins_Note();
        yield return new WaitForSeconds(0.845f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.845f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[5].Heal_Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.845f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[2].Heal_Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.845f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.845f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[3].Heal_Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.845f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.423f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.422f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.211f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.212f);
        Notes[2].Ins_Note();
        Invoke("GameEnd", 7);
    }

    public void GameEnd()
    {
        Scoremanager.Instance.Img_Loading(1);
    }

}
