using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
public class SemyeongSong : MonoBehaviour
{
    [SerializeField] private List<Note_instantiate> Notes;
    void Start()
    {
        StartCoroutine(SemyeongGame());
    }
    IEnumerator SemyeongGame() //³ëÆ®´Â 4ÃÊµÚ¿¡ ¶³¾îÁü
    {
        yield return new WaitForSeconds(7f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.375f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[3].Ins_Note();
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[3].Ins_Note();
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.75f);
        Notes[3].Ins_Note();
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.375f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.5f); //16.5s
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[0].Ins_Note();
        Notes[5].Ins_Note();  //18.75s
        yield return new WaitForSeconds(0.75f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.375f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[0].Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.625f); //30s
        Notes[4].Heal_Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[0].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[2].Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[0].Ins_Note();
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.625f);  //39.125
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.625f); //44.875
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[3].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.625f); //49.875
        Notes[3].Ins_Note();
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[2].Ins_Note();
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f); //51
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f); //53.25
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        yield return new WaitForSeconds(0.250f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f);
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.250f); //55
        Notes[1].Small_Ins_Note();
        Notes[2].Small_Ins_Note();
        Notes[3].Small_Ins_Note();
        Notes[4].Small_Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[4].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[1].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[0].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[3].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[2].Ins_Note();
        yield return new WaitForSeconds(0.5f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        yield return new WaitForSeconds(0.625f);
        Notes[4].Ins_Note();
        Notes[5].Ins_Note();
        Invoke("GameEnd",11);
    }
    public void GameEnd()
    {
        Scoremanager.Instance.Img_Loading(0);
    }

}